language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - tip

install:
  - go get github.com/gin-gonic/gin
  - go get github.com/joho/godotenv
  - go get gopkg.in/mgo.v2
  - go get google.golang.org/api/oauth2/v2
  - go get github.com/stretchr/testify
  - go get github.com/smartystreets/goconvey
